version: '3.7'

services:
  web:
    build: ./mtw_challenge
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./mtw_challenge/:/app
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres:11.5-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: