# Generated by Django 2.2.5 on 2019-09-21 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registro000',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registro', models.CharField(max_length=255)),
                ('data_inicial', models.DateField()),
                ('data_final', models.DateField()),
                ('nome', models.CharField(max_length=255)),
                ('cnpj', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'registro_0000',
            },
        ),
        migrations.CreateModel(
            name='Registro0150',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg', models.CharField(max_length=255)),
                ('cod_participante', models.CharField(max_length=255)),
                ('nome', models.CharField(max_length=255)),
                ('cod_pais', models.IntegerField()),
                ('cnpj', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'registro_0150',
            },
        ),
        migrations.CreateModel(
            name='RegistroC100',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registro', models.CharField(max_length=255)),
                ('cod_participante', models.CharField(max_length=255)),
                ('cod_modelo', models.CharField(max_length=255)),
                ('cod_situacao', models.CharField(max_length=255)),
                ('serie', models.CharField(max_length=255)),
                ('numero_documento', models.IntegerField()),
                ('chave_nfe', models.CharField(max_length=255)),
                ('data_documento', models.DateField()),
                ('data_entrada_saida', models.DateField()),
                ('valor_documento', models.DecimalField(decimal_places=2, max_digits=9)),
            ],
            options={
                'db_table': 'registro_c100',
            },
        ),
        migrations.CreateModel(
            name='RegistroC170',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registro', models.CharField(max_length=255)),
                ('numero_item', models.IntegerField()),
                ('cod_item', models.CharField(max_length=255)),
                ('descricao', models.CharField(max_length=255)),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=9)),
                ('unidade', models.CharField(max_length=255)),
                ('valor_item', models.DecimalField(decimal_places=2, max_digits=9)),
            ],
            options={
                'db_table': 'registro_c170',
            },
        ),
    ]
