# Generated by Django 2.2.5 on 2019-09-21 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registro000',
            name='registro',
        ),
        migrations.RemoveField(
            model_name='registro0150',
            name='reg',
        ),
        migrations.RemoveField(
            model_name='registroc100',
            name='registro',
        ),
        migrations.RemoveField(
            model_name='registroc170',
            name='registro',
        ),
    ]
