# Generated by Django 2.2.5 on 2019-09-21 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190921_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro000',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
