# Generated by Django 2.2.5 on 2019-09-21 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190921_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro0150',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='registroc100',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='registroc170',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
