# Generated by Django 2.2.5 on 2019-09-22 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190921_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro000',
            name='registro',
            field=models.CharField(default='0000', max_length=255),
        ),
        migrations.AddField(
            model_name='registro0150',
            name='registro',
            field=models.CharField(default='0150', max_length=255),
        ),
        migrations.AddField(
            model_name='registroc100',
            name='registro',
            field=models.CharField(default='C100', max_length=255),
        ),
        migrations.AddField(
            model_name='registroc170',
            name='registro',
            field=models.CharField(default='C170', max_length=255),
        ),
    ]
