# Generated by Django 2.2.5 on 2019-09-22 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20190922_2026'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Registro000',
            new_name='Registro0000',
        ),
    ]
