# Generated by Django 2.2.5 on 2019-09-22 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20190922_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro0000',
            name='id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
